"""Url-to-markdown converter backed by trafilatura.

Accepts already-fetched HTML and produces clean Markdown suitable for storage
in the web-pages directory. This service performs **no HTTP** itself — it expects
raw HTML as a string from a prior fetch step.

Outputs:
    * Markdown generated by ``trafilatura.extract`` (images / links / tables).
    * An appended ``## Embedded media`` section listing every ``iframe``/
      ``video``/``source`` ``src`` URL (resolved against the source URL) as a
      markdown link, one per line. Section is omitted when no media elements are
      present.

Persistence is delegated to :meth:`UrlToMarkdownService.persist`, which stores
files under :meth:`~services.FileMapperService.get_web_pages_path`.
"""

import logging
import re
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urljoin, urlparse

from services.file_mapper_service import FileMapperService

logger = logging.getLogger(__name__)


class _MediaSrcCollector(HTMLParser):
    """Collect ``src`` attributes from iframe/video/source elements.

    Handles both opening + closing tags and self-closing variants via
    :meth:`HTMLParser.handle_startendtag`. Duplicates are eliminated by storing
    sources in a ``set``.
    """

    _MEDIA_TAGS = frozenset({"iframe", "video", "source"})

    def __init__(self) -> None:
        super().__init__()
        self.media_srcs: set[str] = set()

    # Self-closing tags need no separate handler: HTMLParser's default
    # ``handle_startendtag`` delegates to ``handle_starttag``.
    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag.lower() in self._MEDIA_TAGS:
            for name, val in attrs:
                if name == "src" and val and val.strip():
                    self.media_srcs.add(val.strip())


class UrlToMarkdownService:
    """Convert already-fetched HTML to markdown and persist under the web-pages directory.

    Contains no HTTP logic; every public method operates purely on in-memory
    inputs and on-disk files underneath ``data/web/pages/``.
    """

    # ------------------------------------------------------------------ Convert

    def convert(self, html: str | bytes, url: str) -> str:
        """Run trafilatura extraction and append an embedded-media section.

        Args:
            html: Already-fetched HTML body. Raw ``bytes`` are handed to
                trafilatura verbatim so it can sniff the document's declared
                charset; the media scan decodes them as UTF-8 with replacement,
                which is lossless for the ASCII ``src`` URLs it looks for.
            url: Canonical source URL (used for relative-link resolution and
                 reported on errors).

        Raises:
            ValueError: If trafilatura returns nothing usable or the inputs are
                empty.
        """
        import trafilatura

        markdown = trafilatura.extract(
            html,
            url=url,
            output_format="markdown",
            include_images=True,
            include_links=True,
            include_tables=True,
            favor_recall=True,
        )

        if not markdown or not markdown.strip():
            raise ValueError(
                f"trafilatura produced no content for URL '{url}'; "
                "the supplied HTML is empty or contains no extractable body."
            )

        collector = _MediaSrcCollector()
        collector.feed(html if isinstance(html, str) else html.decode("utf-8", "replace"))

        media_srcs = sorted(collector.media_srcs)
        if not media_srcs:
            return markdown

        links_block = "\n".join(
            f"[{urljoin(url, src)}]({urljoin(url, src)})" for src in media_srcs
        )
        section = f"\n## Embedded media\n\n{links_block}\n"
        return markdown + section

    # ------------------------------------------------------------- Filename

    def filename_for(self, url: str, extension: str) -> str:
        """Build a flat filename ``<host>--<path-slug>.<extension>``.

        Rules:
        * Full URL is lowercased; the hostname is preserved with dots intact.
        * Inside the path portion, every run of non-alphanumeric characters is
          collapsed to a single ``-``.
        * Leading / trailing ``-`` are trimmed from the resulting slug.
        * The slug is hard-capped at 120 characters.
        * If the path is effectively empty, the result is just ``<host>.<ext>``.
        """
        parsed = urlparse(url.lower())
        host = parsed.hostname or ""

        path = parsed.path or ""
        if path in ("", "/"):
            return f"{host}.{extension}"

        # Drop leading slashes, normalize, trim residual dashes, cap length.
        slug = re.sub(r"[^a-z0-9]+", "-", path.lstrip("/")).strip("-")[:120]
        if slug:
            return f"{host}--{slug}.{extension}"
        return f"{host}.{extension}"

    # ---------------------------------------------------------------- Persist

    def persist(self, content: str, url: str, extension: str) -> Path:
        """Write *content* under the web-pages directory for *url*.

        Creates intermediate directories with ``parents=True`` and
        ``exist_ok=True``. Any existing file at the destination is overwritten.
        Returns the absolute :class:`~pathlib.Path` of the written file.
        """
        fname = self.filename_for(url, extension)
        target = FileMapperService.get_web_pages_path(fname)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        return target.absolute()
