#!/usr/bin/env python3
"""Seed provider_examples with ~1,040 diverse search queries for semantic routing."""

import sqlite3
import os

DB_PATH = os.path.join(os.path.dirname(__file__), "data", "providers.sqlite")

EXAMPLES = {
    # -------------------------------------------------------------------------
    # 1. Wikipedia (id=1) — 200 examples
    # General knowledge, facts, people, places, events, science, history, culture
    # -------------------------------------------------------------------------
    1: [
        # People
        "who was Marie Curie",
        "Albert Einstein biography",
        "life of Genghis Khan",
        "Nikola Tesla inventions and legacy",
        "Queen Victoria reign",
        "Cleopatra history",
        "Leonardo da Vinci",
        "Napoleon Bonaparte",
        "Mahatma Gandhi nonviolent movement",
        "Alexander the Great empire",
        "Abraham Lincoln assassination",
        "Frida Kahlo art and life",
        "Isaac Newton contributions to science",
        "Charles Darwin evolution theory",
        "Aristotle philosophy",
        "Ada Lovelace first programmer",
        "Martin Luther King Jr civil rights",
        "Nelson Mandela apartheid",
        "Galileo Galilei",
        "William Shakespeare plays",
        # Places
        "Great Wall of China",
        "Machu Picchu history",
        "Taj Mahal architecture",
        "Colosseum in Rome",
        "Amazon rainforest",
        "Sahara Desert geography",
        "Mount Everest",
        "Mariana Trench depth",
        "Antarctica ice sheet",
        "Great Barrier Reef",
        "Galápagos Islands wildlife",
        "Nile River length and history",
        "Yellowstone National Park",
        "Angkor Wat temple complex",
        "Pompeii volcanic eruption",
        # Historical events
        "French Revolution causes and timeline",
        "World War I summary",
        "World War II Pacific theater",
        "fall of the Berlin Wall",
        "Cuban Missile Crisis",
        "Industrial Revolution",
        "American Civil War",
        "Russian Revolution 1917",
        "Renaissance period in Europe",
        "the Crusades",
        "Black Death plague",
        "Cold War overview",
        "Apollo 11 moon landing",
        "signing of the Magna Carta",
        "Chernobyl disaster",
        # Science
        "photosynthesis process",
        "how does DNA replication work",
        "theory of relativity explained",
        "what is quantum mechanics",
        "plate tectonics",
        "periodic table of elements",
        "mitochondria cell organelle",
        "electromagnetic spectrum",
        "speed of light",
        "how do vaccines work",
        "Krebs cycle",
        "nuclear fission vs fusion",
        "what is CRISPR gene editing",
        "how do black holes form",
        "general relativity",
        "thermodynamics laws",
        "Schrödinger equation",
        "Hubble Space Telescope",
        "stem cell research",
        "what causes earthquakes",
        # Biology and nature
        "blue whale largest animal",
        "how do bees make honey",
        "octopus intelligence",
        "human circulatory system",
        "types of dinosaurs",
        "how do chameleons change color",
        "coral reef ecosystem",
        "Venus flytrap",
        "migration patterns of birds",
        "symbiosis in nature",
        "what is an amoeba",
        "pangolin endangered species",
        "phototropism in plants",
        "human brain anatomy",
        "evolution of horses",
        # Geography and countries
        "Japan geography and culture",
        "history of Egypt",
        "geography of Brazil",
        "India demographics",
        "Australia wildlife",
        "Switzerland political system",
        "Iceland geothermal energy",
        "New Zealand Maori culture",
        "South Korea economy",
        "Canada provinces and territories",
        # Culture and arts
        "Impressionism art movement",
        "history of jazz music",
        "Baroque architecture",
        "Greek mythology",
        "Norse mythology Odin and Thor",
        "Kabuki theater Japan",
        "Mona Lisa painting",
        "Sistine Chapel ceiling",
        "surrealism art movement",
        "history of cinema",
        # Philosophy and religion
        "Stoicism philosophy",
        "Buddhism four noble truths",
        "existentialism Sartre",
        "Confucianism principles",
        "what is utilitarianism",
        "Plato allegory of the cave",
        "Taoism beliefs",
        "Hinduism caste system",
        "Enlightenment Age thinkers",
        "Socratic method",
        # Technology concepts
        "history of the internet",
        "how does electricity work",
        "what is artificial intelligence",
        "transistor invention",
        "how does GPS work",
        "invention of the printing press",
        "history of aviation",
        "how does fiber optics work",
        "steam engine history",
        "radio wave communication",
        # Sports
        "history of the Olympic Games",
        "FIFA World Cup records",
        "baseball rules and history",
        "Tour de France cycling",
        "sumo wrestling traditions",
        "cricket sport rules",
        "Muhammad Ali boxing career",
        "history of chess",
        "Formula One racing",
        "marathon running origins",
        # Organizations and institutions
        "United Nations history",
        "NATO alliance",
        "World Health Organization",
        "European Union formation",
        "International Space Station",
        "Red Cross organization",
        "CERN particle physics lab",
        "Smithsonian Institution",
        "MIT history",
        "Oxford University",
        # Wars and conflicts
        "Hundred Years War",
        "Vietnam War summary",
        "Korean War",
        "Napoleonic Wars",
        "Peloponnesian War",
        "War of the Roses",
        "Falklands War",
        "Six-Day War",
        "Boer War",
        "Sino-Japanese War",
        # Inventions and discoveries
        "who invented the telephone",
        "discovery of penicillin",
        "invention of the wheel",
        "history of gunpowder",
        "who discovered radioactivity",
        "invention of the compass",
        "Wright brothers first flight",
        "development of the polio vaccine",
        "history of the telescope",
        "who invented dynamite",
        # Miscellaneous knowledge
        "what is the Rosetta Stone",
        "Dead Sea Scrolls",
        "Bermuda Triangle",
        "what is the Fibonacci sequence",
        "seven wonders of the ancient world",
        "how do tides work",
        "what causes the northern lights",
        "Halley's Comet",
        "what is the gold standard",
        "Esperanto language",
        "Roman numeral system",
        "Pythagorean theorem",
        "what is the Doppler effect",
        "how do volcanoes erupt",
        "what is pi in mathematics",
        "Fermat's last theorem",
        "how do glaciers form",
        "what is a supernova",
        "history of democracy",
        "feudal system in medieval Europe",
        "Silk Road ancient trade route",
        "Aztec Empire history",
        "history of the Samurai",
        "Ottoman Empire rise and fall",
        "Mesopotamia cradle of civilization",
        "what is the Higgs boson",
        "history of the English language",
        "how do submarines work",
        "the Renaissance artists and inventions",
        "Treaty of Versailles",
        "what is dark matter",
        "Mayan civilization",
        "history of vaccination",
        "what is a quasar",
        "Viking exploration and settlements",
    ],

    # -------------------------------------------------------------------------
    # 2. Wikidata (id=2) — 100 examples
    # Structured entity queries, properties, relationships, classifications
    # -------------------------------------------------------------------------
    2: [
        "who founded Tesla Motors",
        "capital of Mongolia",
        "population of Tokyo",
        "when was Beethoven born",
        "what country is Zurich in",
        "who is the CEO of Apple",
        "official language of Brazil",
        "currency of Japan",
        "height of the Eiffel Tower",
        "who directed Inception",
        "what continent is Nigeria in",
        "who wrote Pride and Prejudice",
        "area of Russia in square kilometers",
        "who invented the light bulb",
        "what is the chemical symbol for gold",
        "who painted Guernica",
        "nationality of Chopin",
        "when did the Titanic sink",
        "how many moons does Jupiter have",
        "who discovered America",
        "what river flows through Paris",
        "who is the president of France",
        "what sport does Serena Williams play",
        "what genre is Blade Runner",
        "founder of Wikipedia",
        "what language do they speak in Iran",
        "birth date of Mozart",
        "who composed The Four Seasons",
        "what ocean is Hawaii in",
        "parent company of Instagram",
        "death date of Abraham Lincoln",
        "who was the first woman in space",
        "what type of animal is a dolphin",
        "atomic number of carbon",
        "who designed the Sydney Opera House",
        "what country borders France to the east",
        "spouse of Queen Elizabeth II",
        "what mountain range is K2 in",
        "who won Nobel Prize in Literature 2020",
        "headquarters of the United Nations",
        "what is the boiling point of water",
        "who played James Bond in Casino Royale",
        "architect of Fallingwater",
        "what kingdom do fungi belong to",
        "capital of New Zealand",
        "who founded Amazon",
        "what timezone is London in",
        "flag colors of Italy",
        "who authored 1984 the novel",
        "what galaxy is Earth in",
        "ISO country code for Germany",
        "what year was the Eiffel Tower built",
        "who sculpted David",
        "official religion of Thailand",
        "what planet is closest to the Sun",
        "population of Iceland",
        "who patented the telephone",
        "children of Queen Victoria",
        "capital of Burkina Faso",
        "what is the tallest building in the world",
        "who invented the World Wide Web",
        "what dynasty built the Forbidden City",
        "GDP of India",
        "who wrote Don Quixote",
        "mayor of New York City",
        "what species is a bald eagle",
        "founder of the Red Cross",
        "what currency does Switzerland use",
        "who discovered DNA structure",
        "elevation of Denver Colorado",
        "sister city of Tokyo",
        "what language family is Finnish in",
        "who was the first president of the United States",
        "what continent is Argentina on",
        "when was the Suez Canal opened",
        "what is the national flower of Japan",
        "who wrote the Communist Manifesto",
        "latitude of the equator",
        "what is the longest river in Africa",
        "who founded SpaceX",
        "what instrument did Miles Davis play",
        "capital of South Sudan",
        "who discovered oxygen",
        "what classification is a tomato fruit or vegetable",
        "when was Harvard University established",
        "who painted The Starry Night",
        "what is the deepest lake in the world",
        "number of bones in the human body",
        "who choreographed Swan Lake",
        "what country invented paper",
        "melting point of iron",
        "who is buried in the Taj Mahal",
        "total area of Lake Superior",
        "who first synthesized aspirin",
        "national anthem of Canada",
        "what phylum do insects belong to",
        "who designed the Guggenheim Museum",
        "date of Indian independence",
        "what is the smallest country by area",
        "who won the 1969 Super Bowl",
        "publisher of Harry Potter",
    ],

    # -------------------------------------------------------------------------
    # 3. ArXiv (id=3) — 100 examples
    # Academic/research paper queries
    # -------------------------------------------------------------------------
    3: [
        "transformer architecture attention mechanism paper",
        "variational autoencoders latent space representation",
        "graph neural networks for molecular property prediction",
        "reinforcement learning with human feedback RLHF",
        "diffusion models for image generation",
        "quantum error correction surface codes",
        "large language model scaling laws",
        "federated learning privacy preserving machine learning",
        "neural ordinary differential equations",
        "causal inference observational studies",
        "contrastive learning self-supervised representations",
        "topological data analysis persistent homology",
        "Navier-Stokes existence and smoothness",
        "adversarial robustness deep neural networks",
        "Bayesian optimization hyperparameter tuning",
        "multi-agent reinforcement learning cooperation",
        "knowledge distillation model compression",
        "normalizing flows generative models",
        "computational complexity P vs NP",
        "protein folding prediction AlphaFold",
        "meta-learning few-shot classification",
        "GAN training stability mode collapse",
        "point cloud 3D object detection LiDAR",
        "optimal transport Wasserstein distance",
        "neural architecture search automated ML",
        "Riemannian geometry manifold learning",
        "gravitational wave detection LIGO data analysis",
        "zero-shot learning vision language models",
        "stochastic gradient descent convergence rates",
        "tensor decomposition high dimensional data",
        "recurrent neural network vanishing gradients",
        "continual learning catastrophic forgetting",
        "Hamiltonian Monte Carlo sampling methods",
        "sparse mixture of experts scaling",
        "equivariant neural networks symmetry",
        "reward modeling alignment AI safety",
        "entanglement entropy quantum information",
        "Monte Carlo tree search planning",
        "neural radiance fields 3D reconstruction",
        "information geometry Fisher metric",
        "robust statistics heavy-tailed distributions",
        "attention mechanisms sequence modeling",
        "curriculum learning training strategies",
        "spectral graph theory Laplacian eigenvalues",
        "denoising score matching generative models",
        "homomorphic encryption machine learning",
        "mean field theory statistical mechanics",
        "active learning sample efficiency",
        "chain of thought reasoning prompting",
        "domain adaptation distribution shift",
        "spin glass models optimization landscape",
        "multi-modal learning vision language fusion",
        "algorithmic fairness bias mitigation",
        "category theory functional programming",
        "world models model-based reinforcement learning",
        "baryonic acoustic oscillations cosmology",
        "automatic differentiation computational graphs",
        "Ramsey theory combinatorics bounds",
        "object detection YOLO real-time inference",
        "elliptic curve cryptography",
        "neural tangent kernel infinite width",
        "dark matter simulation N-body",
        "language model memorization privacy",
        "convex optimization duality gap",
        "synthetic data generation training",
        "Lie algebra representation theory",
        "spiking neural networks neuromorphic computing",
        "retrieval augmented generation knowledge grounding",
        "lattice QCD quark confinement",
        "energy-based models Boltzmann machines",
        "algebraic topology homotopy type theory",
        "multivariate time series forecasting",
        "quantum supremacy computational advantage",
        "instruction tuning large language models",
        "nonlinear dynamics chaos theory Lyapunov",
        "efficient inference transformer models",
        "topological quantum computing anyons",
        "semi-supervised learning pseudo labels",
        "percolation theory critical phenomena",
        "video understanding temporal modeling",
        "geometric deep learning on graphs and manifolds",
        "constraint satisfaction satisfiability solvers",
        "cosmological perturbation theory inflation",
        "code generation program synthesis neural",
        "operator algebras von Neumann factors",
        "out-of-distribution detection uncertainty estimation",
        "fluid dynamics turbulence modeling LES DNS",
        "Markov decision process policy gradient",
        "knot invariants polynomial Jones",
        "mechanistic interpretability neural networks",
        "compressed sensing sparse recovery RIP",
        "climate model ensemble predictions",
        "cooperative game theory Shapley value",
        "modular forms elliptic curves number theory",
        "slot attention object-centric learning",
        "quantum walks graph algorithms",
        "Bayesian deep learning predictive uncertainty",
        "biomolecular simulation molecular dynamics force field",
        "constitutional AI harmlessness training",
        "ergodic theory measure-preserving transformations",
        "positional encoding rotary embeddings",
    ],

    # -------------------------------------------------------------------------
    # 4. GitHub (id=4) — 80 examples
    # Code/developer: libraries, frameworks, tools, repos
    # -------------------------------------------------------------------------
    4: [
        "Python HTTP client library",
        "React component library UI",
        "Rust async runtime tokio",
        "Go web framework",
        "open source project management tool",
        "TypeScript ORM for PostgreSQL",
        "machine learning framework for edge devices",
        "Kubernetes deployment YAML generator",
        "static site generator Hugo",
        "VS Code extension for linting",
        "Python data validation library pydantic",
        "Docker compose templates microservices",
        "CLI tool for AWS S3",
        "SQLite wrapper for Python",
        "open source video editor",
        "Tailwind CSS component library",
        "authentication library OAuth2 OpenID",
        "WebSocket library for Node.js",
        "terminal file manager written in Go",
        "Terraform provider for CloudFlare",
        "PDF generation library Python",
        "open source monitoring Grafana Prometheus",
        "GraphQL server implementation Python",
        "image processing library Rust",
        "email sending library SMTP",
        "markdown parser JavaScript",
        "test framework for Elixir",
        "serverless framework AWS Lambda",
        "database migration tool Alembic",
        "JSON schema validator",
        "open source calendar app",
        "React Native starter template",
        "logging library structured JSON",
        "caching library Redis client",
        "text search engine Meilisearch",
        "CI/CD pipeline GitHub Actions",
        "WASM runtime browser",
        "SSH client library Python paramiko",
        "code formatter Prettier alternative",
        "task queue Celery alternative lightweight",
        "API gateway Kong Traefik",
        "rate limiting middleware Express",
        "file upload handling multipart",
        "geospatial library PostGIS",
        "browser automation Playwright Puppeteer",
        "CSS-in-JS styled components alternative",
        "protobuf gRPC code generator",
        "open source password manager",
        "dotfiles manager chezmoi",
        "Python type checker mypy",
        "event sourcing library CQRS",
        "load testing tool k6 Locust",
        "natural language processing spaCy",
        "video streaming library HLS",
        "config file parser TOML YAML",
        "dependency injection framework",
        "open source CRM",
        "command line argument parser",
        "cross-platform desktop app Tauri Electron",
        "vector database client Qdrant",
        "barcode QR code generator library",
        "OAuth2 server implementation Go",
        "distributed tracing OpenTelemetry",
        "FFmpeg wrapper library",
        "date time library Luxon dayjs",
        "state management library Zustand",
        "regex builder library readable",
        "web scraping framework Scrapy",
        "open source chat application",
        "binary serialization MessagePack",
        "SQLite full text search extension",
        "notification service push library",
        "form validation React hook form",
        "open source invoicing software",
        "Python ASGI server Uvicorn",
        "Vim Neovim plugin manager",
        "container registry self-hosted",
        "REST API documentation Swagger OpenAPI",
        "diff library text comparison",
        "GPU compute shader library",
    ],

    # -------------------------------------------------------------------------
    # 5. Hacker News (id=5) — 80 examples
    # Tech news, discussions, opinions, industry trends
    # -------------------------------------------------------------------------
    5: [
        "what do developers think about Rust replacing C++",
        "startup raised Series A building AI product",
        "Show HN new programming language",
        "why engineers are leaving big tech companies",
        "discussion on remote work vs return to office",
        "new database claims to be faster than Postgres",
        "Ask HN what are you working on this weekend",
        "YC startup demo day highlights",
        "tech layoffs 2026 discussion",
        "opinion on Apple's new developer tools",
        "why Haskell never went mainstream",
        "blog post about scaling to one million users",
        "Ask HN how do you stay motivated as a solo developer",
        "Google antitrust ruling implications for developers",
        "open source AI model beats proprietary benchmark",
        "discussion about software engineering salaries plateau",
        "new self-hosted alternative to Notion",
        "why SQLite is the most deployed database",
        "Show HN I built a tool to visualize git history",
        "blog post microservices were a mistake",
        "debate about programming language productivity",
        "founder shares lessons from failed startup",
        "tech industry consolidation big five dominance",
        "Ask HN what changed your mind about a technology",
        "EU regulation on AI impact on startups",
        "side project turned into profitable business",
        "why I switched from Mac to Linux for development",
        "discussion Kubernetes is overkill for most teams",
        "new browser engine project not Chromium based",
        "blog post how we reduced our AWS bill by 80 percent",
        "opinion piece on technical debt",
        "Show HN weekend project that got traction",
        "state of WebAssembly adoption",
        "discussion about VC funding winter",
        "serverless vs traditional deployment debate",
        "blog post writing a compiler from scratch",
        "Ask HN best resources for learning systems programming",
        "new privacy-focused search engine launches",
        "cloud provider outage postmortem analysis",
        "debate monorepo vs polyrepo",
        "blog post on burnout in the tech industry",
        "discussion on code review culture",
        "Ask HN how do you handle on-call rotations",
        "breakthrough in battery technology startup",
        "new encryption standard post-quantum",
        "blog post about leaving FAANG for a startup",
        "discussion TypeScript vs JavaScript in 2026",
        "Show HN open source alternative to Figma",
        "thoughts on AI-generated code quality",
        "discussion about the future of web browsers",
        "Ask HN what underrated tools do you use daily",
        "controversy around npm package supply chain attack",
        "blog post on building resilient distributed systems",
        "opinion on LLM coding assistants replacing junior devs",
        "discussion about right to repair legislation tech",
        "Show HN terminal-based productivity app",
        "blog post postgres just keeps getting better",
        "indie hacker revenue milestone post",
        "discussion on ethical AI development practices",
        "Ask HN what programming concepts took you years to understand",
        "new chip architecture challenging ARM and x86",
        "blog post about the complexity of modern frontend",
        "discussion about tech immigration policy changes",
        "Show HN I reverse engineered a proprietary protocol",
        "blog post from a staff engineer about career growth",
        "opinion on subscription fatigue in developer tools",
        "discussion about declining quality of Google search",
        "Ask HN favorite technical blogs to follow",
        "new programming language designed for AI safety",
        "blog post about running a profitable bootstrapped SaaS",
        "discussion on open source sustainability funding",
        "Show HN real-time collaboration engine",
        "reaction to major tech acquisition announcement",
        "Ask HN how do you organize your personal knowledge base",
        "blog post on why we chose boring technology",
        "discussion about browser extension security risks",
        "Show HN CLI tool for managing dotfiles",
        "debate about software licensing GPL vs MIT",
        "discussion on developer experience as a competitive advantage",
        "Ask HN what emerging technology are you most excited about",
    ],

    # -------------------------------------------------------------------------
    # 6. Reddit (id=6) — 100 examples
    # Opinions, recommendations, community advice, personal experience
    # -------------------------------------------------------------------------
    6: [
        "best noise cancelling headphones under 200",
        "is the Dyson vacuum worth the price",
        "has anyone tried intermittent fasting for weight loss",
        "best budget gaming laptop 2026",
        "how do I remove coffee stains from white shirt",
        "is it worth learning Python in 2026",
        "best streaming service for documentaries",
        "my landlord won't fix the heater what are my options",
        "favorite meal prep recipes for busy weekdays",
        "best mattress for back pain",
        "how do I deal with a noisy neighbor",
        "is a standing desk actually better for you",
        "best starter camera for photography beginner",
        "what's the best way to learn guitar on your own",
        "recommendations for a good therapist in Austin",
        "how to negotiate salary at a new job",
        "best credit card for travel rewards",
        "what supplements actually work for energy",
        "is buying a house in 2026 a good idea",
        "best dog breed for apartment living",
        "how to get rid of fruit flies in kitchen",
        "best running shoes for flat feet",
        "what's the best VPN for privacy",
        "how do I stop procrastinating on important tasks",
        "best mechanical keyboard for typing",
        "is creatine safe to take daily",
        "tips for first time home buyer",
        "best carry on luggage for international travel",
        "how to fix a running toilet",
        "what's the best way to learn a new language",
        "best electric toothbrush recommendation",
        "how do I cook the perfect steak",
        "best air purifier for allergies",
        "has anyone used Duolingo to actually become fluent",
        "best monitor for working from home",
        "how to get better sleep naturally",
        "what's the cheapest way to ship packages internationally",
        "best robot vacuum for pet hair",
        "how do I remove a stripped screw",
        "best protein powder that actually tastes good",
        "is it worth getting a bidet",
        "how to fix squeaky hardwood floors",
        "best winter jacket for extreme cold",
        "what's the best way to invest 10000 dollars",
        "how to deal with imposter syndrome at work",
        "best instant pot recipes for beginners",
        "how do I unclog a drain without chemicals",
        "best sunscreen that doesn't leave white cast",
        "is a home gym worth the investment",
        "how to train a puppy to stop biting",
        "best way to clean a cast iron skillet",
        "has anyone switched from iPhone to Android",
        "best plants for a dark apartment",
        "how do I dispute a charge on my credit card",
        "best wireless earbuds for working out",
        "what should I know before adopting a cat",
        "best way to organize a small closet",
        "tips for surviving a long haul flight",
        "how to deal with anxiety without medication",
        "best blender for making smoothies",
        "is grad school worth it financially",
        "best board games for adults game night",
        "how do I fix a leaky faucet myself",
        "best thermostat for saving on energy bills",
        "what's the most reliable used car to buy",
        "how to get paint off hardwood floors",
        "best espresso machine for home under 500",
        "tips for moving to a new city alone",
        "how to stop a dog from barking at everything",
        "best tool set for basic home repairs",
        "is Planet Fitness a good gym for beginners",
        "how to clean mold in bathroom",
        "best backpack for daily commute",
        "how do I politely decline a wedding invitation",
        "best speakers for a living room setup",
        "what to do when your car battery dies",
        "how to make sourdough bread from scratch",
        "best ergonomic office chair under 500",
        "how do I ask for a raise at work",
        "tips for reducing screen time",
        "best way to learn to swim as an adult",
        "how to sharpen kitchen knives properly",
        "is renting forever actually bad financially",
        "best slow cooker recipes set and forget",
        "how to get rid of mice in the house",
        "best dash cam recommendation",
        "what should I pack for a camping trip",
        "how to fix a dent in a car door",
        "best podcast app for Android",
        "how do I tell my boss I'm overwhelmed",
        "best hiking boots for wide feet",
        "is it okay to eat eggs every day",
        "how to clean white sneakers",
        "best way to store leftover food longer",
        "has anyone tried cold plunge therapy",
        "best router for large house WiFi coverage",
        "how to compost in an apartment",
        "best eye cream that actually reduces dark circles",
        "tips for meal planning on a budget",
        "how do I hang heavy shelves on drywall",
    ],

    # -------------------------------------------------------------------------
    # 7. Google News (id=7) — 80 examples
    # Current events, breaking news, politics, world events
    # -------------------------------------------------------------------------
    7: [
        "latest news about the Ukraine conflict",
        "what happened in Congress today",
        "breaking news earthquake",
        "stock market today",
        "latest COVID variant update",
        "election results today",
        "recent hurricane damage report",
        "current situation in the Middle East",
        "Federal Reserve interest rate decision today",
        "major wildfire update California",
        "news about the Supreme Court ruling",
        "latest tech company layoffs",
        "today's sports scores NBA",
        "breaking news mass shooting",
        "latest immigration policy changes",
        "what's happening with the debt ceiling",
        "today's weather severe storm warnings",
        "latest cryptocurrency regulation news",
        "airline strike news today",
        "current oil prices and OPEC decision",
        "latest UN climate summit news",
        "presidential approval ratings today",
        "new trade agreement announced",
        "latest police reform legislation",
        "today's inflation report CPI data",
        "breaking news hostage situation",
        "latest NASA mission update",
        "current border crisis developments",
        "news about social media regulation",
        "latest pharmaceutical drug approval FDA",
        "today's European Central Bank decision",
        "major cyber attack news today",
        "latest school shooting incident",
        "current energy crisis Europe",
        "news about autonomous vehicle accident",
        "latest housing market data report",
        "today's unemployment numbers",
        "breaking news volcanic eruption",
        "latest sanctions against Russia",
        "news about teacher strikes",
        "current flooding disaster update",
        "latest news on AI regulation",
        "today's NATO summit outcomes",
        "breaking news plane crash",
        "latest labor union negotiations",
        "current situation Taiwan strait",
        "today's gold price surge",
        "latest news space debris collision",
        "new minimum wage legislation",
        "recent data breach company hack",
        "latest political scandal investigation",
        "today's UK Parliament debate",
        "current drought conditions water restrictions",
        "latest recall consumer product safety",
        "news about pension reform protests",
        "today's G7 summit communiqué",
        "latest pipeline explosion incident",
        "current supply chain disruption shipping",
        "news about hostage release negotiations",
        "latest coral bleaching event report",
        "today's jobs report payroll numbers",
        "breaking news bridge collapse",
        "latest news EV tariff policy",
        "current bird flu outbreak",
        "today's UN Security Council vote",
        "latest nuclear talks Iran deal",
        "news about railroad worker agreement",
        "current Australian bushfire season",
        "latest news semiconductor export controls",
        "today's GDP growth numbers quarterly",
        "breaking news prison escape",
        "latest news oil spill cleanup",
        "current heat wave death toll",
        "news about student loan forgiveness update",
        "latest military deployment announcement",
        "today's WHO pandemic declaration",
        "current situation Venezuela opposition",
        "latest news about SpaceX launch",
        "breaking corporate merger acquisition news",
        "latest developments in ceasefire negotiations",
    ],

    # -------------------------------------------------------------------------
    # 8. Stack Exchange (id=8) — 80 examples
    # Technical Q&A, errors, debugging, configuration
    # -------------------------------------------------------------------------
    8: [
        "how to fix segmentation fault in C program",
        "why does my Python script throw ModuleNotFoundError",
        "how to center a div vertically and horizontally CSS",
        "JavaScript TypeError cannot read property of undefined",
        "how to set up SSH key authentication Linux",
        "MySQL query slow on large table optimization",
        "React useEffect infinite loop how to fix",
        "how to parse JSON in bash script",
        "nginx 502 bad gateway reverse proxy",
        "Docker container exits immediately after starting",
        "git merge conflict how to resolve",
        "how to install specific version of npm package",
        "Python virtual environment not activating Windows",
        "how to redirect HTTP to HTTPS in Apache",
        "Java OutOfMemoryError heap space increase",
        "how to write a LEFT JOIN in SQL",
        "TypeScript error type X is not assignable to type Y",
        "how to configure CORS in Express.js",
        "Linux permission denied even with sudo",
        "how to flatten a nested list in Python",
        "Postgres connection refused port 5432",
        "how to create a cron job that runs every 5 minutes",
        "Python pandas merge two dataframes on column",
        "webpack build fails Module not found error",
        "how to set environment variables in Dockerfile",
        "bash script if else syntax",
        "how to convert string to datetime in Python",
        "CSS flexbox vs grid when to use which",
        "kubectl pod stuck in CrashLoopBackOff",
        "how to implement binary search in Java",
        "SQLite database is locked error",
        "how to use async await in JavaScript",
        "regex to match email address pattern",
        "how to mount NFS share on Ubuntu",
        "React state not updating immediately after setState",
        "how to extract tar.gz file Linux command",
        "Python requests library SSL certificate verify failed",
        "how to rollback a git commit already pushed",
        "how to read a file line by line in Python",
        "Terraform state locked how to unlock",
        "how to enable swap space on Linux",
        "Vue.js computed property not updating",
        "how to pass arguments to a Makefile target",
        "systemd service fails to start ExecStart",
        "how to cast integer to string in Go",
        "PostgreSQL duplicate key violates unique constraint",
        "how to find and kill process on specific port",
        "Python decorators explained with examples",
        "how to install CUDA toolkit Ubuntu",
        "GitHub Actions workflow syntax error",
        "how to use iptables to block an IP",
        "Ansible playbook fails with unreachable host",
        "how to configure logrotate for custom log file",
        "TypeScript generic function type constraint",
        "how to deep copy an object in JavaScript",
        "UFW firewall allow specific port",
        "how to check disk space usage Linux",
        "Python multiprocessing vs threading when to use",
        "how to change default Java version on Mac",
        "SQL window function ROW_NUMBER partition by",
        "Rust borrow checker error cannot borrow as mutable",
        "how to set up virtual host Apache",
        "Docker build context too large",
        "how to use sed to replace text in file",
        "Flask app not accessible from outside localhost",
        "how to write unit test in pytest fixtures",
        "Elasticsearch query DSL filter vs must",
        "how to configure Prometheus to scrape metrics",
        "npm ERR peer dependency conflict resolution",
        "how to implement middleware in Django",
        "tmux session not found after reboot",
        "how to optimize pandas DataFrame memory usage",
        "certbot SSL certificate renewal fails",
        "how to create a systemd timer instead of cron",
        "bash variable expansion double quotes vs single",
        "how to use group by having clause SQL",
        "Kubernetes service not routing to pods",
        "how to debug memory leak in Node.js",
        "Python ImportError circular import how to fix",
        "how to write a Dockerfile for multi-stage build",
    ],

    # -------------------------------------------------------------------------
    # 9. Open Library (id=9) — 80 examples
    # Books, authors, literary works, ISBN, reading recommendations
    # -------------------------------------------------------------------------
    9: [
        "books by Haruki Murakami",
        "novels about time travel",
        "ISBN 978-0-06-112008-4",
        "best books on stoic philosophy",
        "Gabriel García Márquez bibliography",
        "science fiction novels about artificial intelligence",
        "classic Russian literature authors",
        "Pulitzer Prize winning novels list",
        "children's books by Roald Dahl",
        "best books about the French Revolution",
        "Toni Morrison novels in order",
        "fantasy series similar to Lord of the Rings",
        "books about cognitive psychology",
        "mystery novels by Agatha Christie",
        "best history books about ancient Rome",
        "graphic novels for adults recommendations",
        "books on personal finance for beginners",
        "poetry collections by Maya Angelou",
        "dystopian novels like 1984",
        "books about the history of mathematics",
        "Kurt Vonnegut complete works",
        "best memoirs by women authors",
        "philosophical novels existentialism",
        "books about machine learning for beginners",
        "African American literature classics",
        "horror novels by Stephen King",
        "books about World War II firsthand accounts",
        "Japanese literature modern classics",
        "books on evolutionary biology",
        "young adult novels about mental health",
        "books by Oliver Sacks neurology",
        "spy thriller novels John le Carré",
        "books about the history of jazz",
        "Latin American magical realism novels",
        "best books on leadership and management",
        "Virginia Woolf novels",
        "books about climate change and environment",
        "detective fiction Sherlock Holmes editions",
        "books on ancient Egyptian history",
        "contemporary literary fiction award winners",
        "cookbooks by Julia Child",
        "books about the Apollo space program",
        "short story collections by Jorge Luis Borges",
        "books on meditation and mindfulness",
        "Philip K Dick science fiction novels",
        "books about the Silk Road history",
        "feminist literature classics",
        "books on quantum physics for laypeople",
        "novels set in Victorian England",
        "books by James Baldwin essays",
        "best books about American Civil War",
        "travel writing books about Southeast Asia",
        "books about indigenous peoples history",
        "Dostoevsky novels in recommended reading order",
        "books on cryptography and code breaking",
        "Ursula K Le Guin earthsea series",
        "books about the Ottoman Empire",
        "Nobel Prize literature winners recent",
        "autobiographies of scientists",
        "books about urban planning and cities",
        "Octavia Butler science fiction works",
        "books on behavioral economics",
        "classic Chinese literature four great novels",
        "books about music theory fundamentals",
        "war novels All Quiet on the Western Front editions",
        "books by David Attenborough nature",
        "comics and graphic novels about history",
        "books about artificial intelligence ethics",
        "Irish literature James Joyce Ulysses editions",
        "books on investing by Warren Buffett",
        "southern gothic novels Flannery O'Connor",
        "books about the brain and consciousness",
        "translated Scandinavian crime fiction",
        "books on philosophy of science",
        "picture books for toddlers bestsellers",
        "historical fiction set in ancient Greece",
        "books about the Internet and digital culture",
        "anthology of American poetry",
        "novels about immigration experience",
        "books on woodworking for beginners",
    ],

    # -------------------------------------------------------------------------
    # 10. MusicBrainz (id=10) — 80 examples
    # Music metadata: artists, albums, songs, discography
    # -------------------------------------------------------------------------
    10: [
        "songs by Radiohead",
        "albums by Miles Davis discography",
        "who recorded Bohemian Rhapsody",
        "Kendrick Lamar album release dates",
        "what album is Stairway to Heaven on",
        "band members of Fleetwood Mac",
        "Beyoncé discography complete",
        "songs on Abbey Road tracklist",
        "genre of Aphex Twin",
        "Daft Punk albums in order",
        "who produced To Pimp a Butterfly",
        "Billie Holiday recordings",
        "Pink Floyd Dark Side of the Moon tracks",
        "Taylor Swift album Folklore songs",
        "John Coltrane A Love Supreme musicians",
        "Nirvana Nevermind release date",
        "Bob Marley and the Wailers albums",
        "what label is Adele signed to",
        "Beethoven Symphony No 9 recordings",
        "Arctic Monkeys debut album",
        "who wrote Hallelujah Leonard Cohen",
        "Bjork album discography",
        "Led Zeppelin physical graffiti tracklist",
        "Bach cello suites performers recordings",
        "Frank Ocean studio albums",
        "Stevie Wonder songs in the key of life tracks",
        "Tame Impala Currents release year",
        "David Bowie Ziggy Stardust album info",
        "Ella Fitzgerald songbook recordings",
        "what genre is Burial",
        "Nina Simone discography",
        "Kanye West My Beautiful Dark Twisted Fantasy credits",
        "The Beatles complete singles",
        "Joni Mitchell Blue album songs",
        "who played bass on Kind of Blue",
        "Talking Heads albums chronological",
        "Massive Attack Mezzanine tracklist",
        "Aretha Franklin greatest hits recordings",
        "Vampire Weekend discography",
        "who sang Jolene originally",
        "Joy Division Unknown Pleasures release info",
        "Fela Kuti albums",
        "Bon Iver For Emma Forever Ago songs",
        "Wu-Tang Clan 36 Chambers credits",
        "Chopin nocturnes recordings",
        "Tyler the Creator album list",
        "The Smiths songs by Morrissey and Marr",
        "Sade albums and singles",
        "what year was Thriller released Michael Jackson",
        "Phoebe Bridgers Punisher tracks",
        "Kraftwerk electronic music albums",
        "Outkast Aquemini tracklist",
        "Debussy Clair de Lune recordings",
        "SZA CTRL songs",
        "Portishead Dummy release date",
        "Bob Dylan Highway 61 Revisited songs",
        "Solange A Seat at the Table credits",
        "who drummed for Led Zeppelin",
        "Childish Gambino discography",
        "Pavement Crooked Rain album info",
        "Erykah Badu Baduizm tracklist",
        "Thom Yorke solo albums",
        "The Cure Disintegration songs",
        "Janelle Monáe albums",
        "Mogwai Young Team release info",
        "Lauryn Hill Miseducation album credits",
        "My Bloody Valentine Loveless tracks",
        "A Tribe Called Quest albums",
        "what instruments does Thundercat play",
        "Sigur Rós albums discography",
        "Fiona Apple Fetch the Bolt Cutters songs",
        "Boards of Canada Music Has the Right to Children",
        "D'Angelo Voodoo album musicians",
        "Mac DeMarco discography",
        "King Crimson In the Court of the Crimson King",
        "Mitski albums in order",
        "MF DOOM discography and aliases",
        "Beach House Depression Cherry tracks",
        "Grimes Art Angels release year",
        "Herbie Hancock Head Hunters album credits",
    ],

    # -------------------------------------------------------------------------
    # 11. iTunes (id=11) — 80 examples
    # Podcasts, movies, TV shows, apps, audiobooks, media
    # -------------------------------------------------------------------------
    11: [
        "best true crime podcast",
        "The Office TV show",
        "movie called Interstellar",
        "audiobook of Sapiens by Yuval Noah Harari",
        "podcast about history Hardcore History",
        "Stranger Things Netflix series",
        "best meditation app",
        "comedy movie Will Ferrell",
        "Serial podcast season one",
        "documentary about climate change",
        "audiobook version of Dune",
        "best science podcast for commute",
        "Breaking Bad TV series",
        "weather app with radar",
        "podcast about business entrepreneurship",
        "horror movie released 2025",
        "Radiolab podcast episodes",
        "animated movie for kids Pixar",
        "fitness tracking app Apple Watch",
        "podcast about psychology and behavior",
        "The Crown TV show Netflix",
        "recipe and cooking app",
        "audiobook Stephen King It",
        "best interview podcast",
        "movie directed by Christopher Nolan",
        "language learning app Spanish",
        "This American Life podcast",
        "TV show about space exploration sci fi",
        "habit tracker app recommendation",
        "audiobook narrated by Morgan Freeman",
        "podcast about technology and startups",
        "romantic comedy movie 2024",
        "The Daily podcast New York Times",
        "drawing and illustration app iPad",
        "true crime documentary series",
        "best sleep sounds app",
        "podcast about philosophy Philosophize This",
        "action thriller movie recent release",
        "budgeting app personal finance",
        "audiobook of Becoming by Michelle Obama",
        "comedy podcast conan needs a friend",
        "nature documentary David Attenborough",
        "note taking app for students",
        "movie musical greatest showman",
        "podcast about economics Freakonomics",
        "TV show game of thrones",
        "calorie counting app",
        "audiobook fantasy series",
        "investigative journalism podcast",
        "sci fi movie aliens space",
        "photo editing app iPhone",
        "podcast about world news global affairs",
        "TV show sitcom modern family",
        "task management app GTD",
        "audiobook self improvement atomic habits",
        "movie about artificial intelligence",
        "podcast about sports and athletes",
        "TV show crime drama mindhunter",
        "password manager app",
        "audiobook biography Steve Jobs",
        "podcast about food and cooking",
        "indie film drama coming of age",
        "music production app GarageBand",
        "TV show about cooking competition",
        "podcast about parenting",
        "war movie saving private ryan",
        "reading app Kindle alternative",
        "audiobook Harry Potter complete series",
        "podcast about design and creativity",
        "TV show thriller suspense",
        "VPN app for iPhone",
        "children's audiobook bedtime stories",
        "podcast about mindfulness and meditation",
        "movie biographical historical drama",
        "weather widget app",
        "audiobook science brief history of time",
        "podcast about relationships and dating",
        "TV show comedy schitt's creek",
        "journaling app daily diary",
        "best podcast for learning about AI",
    ],

    # -------------------------------------------------------------------------
    # 12. Nominatim (id=12) — 80 examples
    # Geography, places, addresses, landmarks, locations
    # -------------------------------------------------------------------------
    12: [
        "where is Reykjavik",
        "address of the White House Washington DC",
        "location of the Louvre Museum Paris",
        "coordinates of Mount Kilimanjaro",
        "where is Timbuktu",
        "postal code for 10 Downing Street London",
        "neighborhood of Central Park New York",
        "where is Patagonia located",
        "address of Buckingham Palace",
        "city of Angkor Wat Cambodia",
        "where is the Panama Canal",
        "location of Silicon Valley",
        "coordinates of the South Pole",
        "where is Lake Titicaca",
        "address of the Kremlin Moscow",
        "where is the Serengeti",
        "postal code for Times Square New York",
        "location of the Brandenburg Gate Berlin",
        "where is Zanzibar",
        "coordinates of the Golden Gate Bridge",
        "city of Petra Jordan",
        "where is Machu Picchu located exactly",
        "address of the Sydney Opera House",
        "neighborhood of Shibuya Tokyo",
        "where is Bora Bora",
        "location of the Acropolis Athens",
        "postal code area of Soho London",
        "where is the Dead Sea",
        "coordinates of Easter Island",
        "where is Chernobyl located",
        "address of the Vatican City",
        "location of Niagara Falls",
        "where is the Strait of Gibraltar",
        "neighborhood of Montmartre Paris",
        "postal code for Hollywood Los Angeles",
        "where is the Gobi Desert",
        "coordinates of Stonehenge",
        "location of the Suez Canal",
        "where is Transylvania Romania",
        "address of the Colosseum Rome",
        "city and country of Dubrovnik",
        "where is Cappadocia Turkey",
        "location of the Great Barrier Reef",
        "postal code for Oxford Street London",
        "where is the Maldives",
        "coordinates of the North Pole",
        "where is Mont Blanc",
        "address of the Taj Mahal Agra",
        "neighborhood of Georgetown Washington DC",
        "where is Lake Baikal",
        "location of Victoria Falls",
        "where is the Ross Ice Shelf",
        "city of Hagia Sophia",
        "postal code for the Champs-Élysées Paris",
        "where is Kilimanjaro which country",
        "coordinates of the Leaning Tower of Pisa",
        "location of the Galápagos Islands",
        "where is the fjords of Norway",
        "address of the Lincoln Memorial",
        "neighborhood of Brooklyn Heights",
        "where is the Atacama Desert",
        "location of Mauna Kea Hawaii",
        "postal code for Red Square Moscow",
        "where is the Danube River",
        "coordinates of Christ the Redeemer Rio",
        "where is the Black Forest Germany",
        "location of the Terracotta Army Xian",
        "city of the Alhambra Spain",
        "where is Santorini",
        "address of Central Station Amsterdam",
        "postal code for Ginza Tokyo",
        "where is the Amalfi Coast",
        "location of the Ring of Kerry Ireland",
        "where is the Okavango Delta",
        "coordinates of Table Mountain Cape Town",
        "where is Loch Ness",
        "location of the DMZ Korean peninsula",
        "neighborhood of Le Marais Paris",
        "where is the Bay of Fundy",
        "address of the Parthenon Athens Greece",
    ],
}


def main():
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    # Clear existing examples
    cur.execute("DELETE FROM provider_examples")
    print("Cleared existing provider_examples.")

    # Insert all examples
    total = 0
    for provider_id, queries in sorted(EXAMPLES.items()):
        for query in queries:
            cur.execute(
                "INSERT INTO provider_examples (provider_id, example_query) VALUES (?, ?)",
                (provider_id, query),
            )
        count = len(queries)
        total += count
        # Fetch provider name for display
        cur.execute("SELECT name FROM providers WHERE id = ?", (provider_id,))
        row = cur.fetchone()
        name = row[0] if row else f"id={provider_id}"
        print(f"  {name:<16} (id={provider_id}): {count:>4} examples")

    conn.commit()
    conn.close()

    print(f"\nTotal examples inserted: {total}")


if __name__ == "__main__":
    main()
