"""Provider credential-reveal action — nested resource under /api/providers/api-key.

Covers:
- GET /api/providers/api-key/<id>  → get (the stored provider's decrypted key)

The edit form hides the credential behind a "Change API key" button; pressing it
asks here, so the field can be filled with what is actually stored rather than a
mask the operator would have to overwrite blind. Reading is all this does: the
key is decrypted by the same accessor every other provider read path already uses
(``ProviderDbService.get_provider_by_id``), and the route is generated by
:class:`~api.action.Action`, so it sits behind the same session auth — and the
same cookie-only restriction — as the rest of the provider admin surface.

Only the id-addressed form is meaningful — a call with no id 404s, matching the
discoverable-tools precedent (api/actions/mcp_clients/discoverable.py).
"""

from __future__ import annotations

from typing import ClassVar, cast

from flask.typing import ResponseReturnValue

from api.action import Action
from api.endpoint import DocumentedResponse
from api.response.provider_credential import ProviderCredential
from exceptions import NotFoundError
from services.provider_db_service import ProviderDbService


class ProviderApiKey(Action):
    """Action returning one stored provider's decrypted API key."""

    id_type: ClassVar[type[int] | type[str]] = int
    cookie_only_methods: ClassVar[frozenset[str]] = frozenset({"get"})
    response_dto = {"get": DocumentedResponse(ProviderCredential)}

    def get(self, id: int | str) -> ResponseReturnValue:
        """Return the decrypted API key stored against this provider.

        Raises:
            NotFoundError: called without an id, or the id names no provider.

        Returns:
            ProviderCredential — ``api_key`` is null when the row stores none or
            the vault is locked.
        """
        if self.is_create(id):
            raise NotFoundError("Not found")
        row = ProviderDbService().get_provider_by_id(cast(int, id))
        if row is None:
            raise NotFoundError("Provider not found")
        return ProviderCredential(
            id=cast(int, row["id"]),
            api_key=cast("str | None", row.get("api_key")),
        ).single()
