from collections.abc import Callable
from typing import TypeVar

_F = TypeVar("_F", bound=Callable[..., object])
_C = TypeVar("_C", bound=type)

class Resource:
    def __init__(self, *args: object, **kwargs: object) -> None: ...

class Namespace:
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    # Registered swagger models, populated by schema_model/register_dto and
    # referenced via ``model=ns.models["Name"]`` / ``@ns.expect(model)``.
    models: dict[str, object]
    def route(self, *args: object, **kwargs: object) -> Callable[[_C], _C]: ...
    def response(self, *args: object, **kwargs: object) -> Callable[[_F], _F]: ...
    def param(self, *args: object, **kwargs: object) -> Callable[[_F], _F]: ...
    def expect(self, *args: object, **kwargs: object) -> Callable[[_F], _F]: ...
    def produces(self, *args: object, **kwargs: object) -> Callable[[_F], _F]: ...
    def schema_model(self, name: str, schema: dict[str, object]) -> object: ...

class Api:
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    models: dict[str, object]
    def add_namespace(self, *args: object, **kwargs: object) -> None: ...
    def init_app(self, *args: object, **kwargs: object) -> None: ...
    def schema_model(self, name: str, schema: dict[str, object]) -> object: ...