from collections.abc import Callable
from typing import TypeVar

_F = TypeVar("_F", bound=Callable[..., object])
_C = TypeVar("_C", bound=type)

class Resource:
    def __init__(self, *args: object, **kwargs: object) -> None: ...

class Namespace:
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def route(self, *args: object, **kwargs: object) -> Callable[[_C], _C]: ...
    def response(self, *args: object, **kwargs: object) -> Callable[[_F], _F]: ...
    def param(self, *args: object, **kwargs: object) -> Callable[[_F], _F]: ...

class Api:
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def add_namespace(self, *args: object, **kwargs: object) -> None: ...
    def init_app(self, *args: object, **kwargs: object) -> None: ...