"""REST endpoints for the subagents namespace — async-delegate (subagent)
lifecycle for the Processes panel.

Routes (generated by the Endpoint base):
    GET    /api/subagents/all     Active async delegates (hydrates the panel
                                   on load/reconnect, since WS push is missed
                                   while away). Paginated.
    DELETE /api/subagents/<id>    Cancel a running delegate by its sub_id
                                   (the panel's per-row stop control). Always
                                   200 — see :meth:`SubagentsEndpoint.delete`.

A delegate is keyed by its own ``sub_id``, NOT a turn_id: backgrounded calls
are fire-and-notify and outlive the ACT iteration that spawned them, so
stopping one is independent of interrupting a turn (``DELETE
/api/thread/<turn_id>``, api/threads.py). The delegate's own cancel_event is
what gets set — see services/async_delegate_runner.py.
"""

from __future__ import annotations

import logging
from typing import ClassVar, cast

from flask.typing import ResponseReturnValue

from api.endpoint import DocumentedResponse, Endpoint
from api.response.subagent import Subagent, SubagentStopResult
from services.log_utils import safe
from services.time_utils import parse_utc

logger = logging.getLogger(__name__)


class SubagentsEndpoint(Endpoint):
    """REST endpoints for async-delegate (subagent) lifecycle.

    Backgrounded tool calls (async delegates) run on daemon threads outside
    any turn's lifetime; this group lets the Processes panel hydrate its
    active list and cancel a running delegate. See
    services/async_delegate_runner.py for the delegate lifecycle itself.
    """

    id_type: ClassVar[type[int] | type[str]] = str
    response_dto = {
        "get_all": DocumentedResponse(Subagent, listing=True),
        "delete": DocumentedResponse(SubagentStopResult, not_found=False),  # ack-style: always 200
    }

    def slug(self) -> str:
        return "subagents"

    def get_all(self, page: int = 1, limit: int = 20) -> ResponseReturnValue:
        """Active async delegates — hydrates the Processes panel on
        load/reconnect, since WS push events are missed while the client is
        disconnected. Each row carries the tool name, the model's summary of
        what it's doing, and when it started.

        Args:
            page: Page number (1-indexed).
            limit: Items per page.

        Returns:
            Paginated list of Subagent DTOs.
        """
        from services.async_delegate_runner import async_delegate_runner  # noqa: PLC0415

        rows = async_delegate_runner.active()
        items = [
            Subagent(
                sub_id=cast(str, row["sub_id"]),
                tool_name=cast(str, row["tool_name"]),
                summary=cast(str | None, row["summary"]),
                started_at=parse_utc(cast(str, row["started_at"])),
            )
            for row in rows
        ]
        total = len(items)
        start = (page - 1) * limit
        end = start + limit
        page_items = items[start:end]
        return Subagent.listing(page_items, page=page, limit=limit, total=total)

    def delete(self, id: int | str) -> ResponseReturnValue:
        """Cancel a running async delegate — the Processes panel's per-row
        stop control. Sets the delegate's cancel_event (it exits at the next
        ACT boundary); an unknown/finished id is a harmless not_found ack,
        NEVER a 404 — delegates finish on their own, and a 404 would error
        the panel on a benign race. Addressed by sub_id, not turn_id — a
        backgrounded delegate is independent of its spawning turn.

        Args:
            id: Async delegate id (sub_id).

        Returns:
            SubagentStopResult ack — cancelled=True on success, else
            reason="not_found" (always 200).
        """
        from services.async_delegate_runner import async_delegate_runner  # noqa: PLC0415

        sub_id = cast(str, id)
        if async_delegate_runner.cancel(sub_id):
            logger.info("[Subagents API] cancel delivered to delegate %s", safe(sub_id[:8]))
            return SubagentStopResult(cancelled=True).single()
        return SubagentStopResult(reason="not_found").single()
