"""REST endpoints for the threads namespace — the thread resource, addressed by turn_id.

Routes (generated by the Endpoint base):
    GET    /api/threads/all       Collapsed thread feed, most-recently-active
                                  first. Paginated; a non-empty ``q`` searches.
    GET    /api/threads/<id>      One turn's full block — the websocket-refetch
                                  and expand-on-click read.
    POST   /api/threads/<id>      Send. ``-1`` starts a new thread; a real id
                                  replies into that one. multipart/form-data.
    DELETE /api/threads/<id>      Interrupt the running turn (the stop button).

Reads are GET, sends are POST, interrupt is DELETE; the turn_id is path-only,
never in the body. The path speaks the MessageProcessor constructor's own
language — ``-1`` is its unset sentinel, so the send needs no mapping layer, and
a supplied id naming no existing turn is rejected by the constructor. The send
returns the turn's freshly-opened turn_execution row (allocated synchronously,
so the surface holds the handle with no websocket round-trip); live output then
surfaces via the ``updated`` signal → REST pull, plus a ``turn_execution`` frame
on every lifecycle flip. Every route is cookie-only: this is the human chat
surface, and a bearer wrapper must never speak into it on its own behalf.
"""

from __future__ import annotations

import logging
import uuid
from collections.abc import Sequence
from typing import ClassVar, cast

from flask import request
from flask.typing import ResponseReturnValue

from api.endpoint import DocumentedResponse, Endpoint
from api.request import Request
from api.response.response import Response
from api.response.threads import ThreadSummary, TurnBlock, TurnExecution, TurnStopResult
from api.thread_scope import ThreadScope
from models.transcript import Transcript
from services.turn_serializer_service import get_service as _serializer

logger = logging.getLogger(__name__)


class ThreadsEndpoint(Endpoint):
    """The thread resource: feed, per-turn block, send, and interrupt.

    A turn (thread) is many transcript rows sharing one ``turn_id``, scoped to
    the channel its :class:`~api.thread_scope.ThreadScope` resolves — turn_ids
    are only unique per channel.
    """

    id_type: ClassVar[type[int] | type[str]] = int
    max_limit: ClassVar[int] = 120
    _post_may_create: ClassVar[bool] = False  # a new thread still answers 200 with its row
    cookie_only_methods: ClassVar[frozenset[str]] = frozenset({"get_all", "get", "post", "delete"})

    response_dto = {
        "get_all": DocumentedResponse(ThreadSummary, listing=True),
        # An unknown turn_id serialises to an empty block rather than 404 — the
        # surface refetches turns it may have raced away from.
        "get": DocumentedResponse(TurnBlock, not_found=False),
        "post": DocumentedResponse(
            TurnExecution,
            extras=(
                (422, "Empty message and no files"),
                (500, "Failed to open turn execution"),
            ),
        ),
        "delete": DocumentedResponse(TurnStopResult, not_found=False),  # ack-style: always 200
    }

    _EXCLUDE_ROLES = ("subagent_return",)
    """Roles that never form a thread of their own in the feed."""

    _MAX_FILES = 10
    _MSG_REQUIRED = "message required"
    _FILE_PLACEHOLDER = "[File attached]"

    def get_all(self, page: int = 1, limit: int = 20) -> ResponseReturnValue:
        """The collapsed thread feed, most-recently-active first. A non-empty
        ``q`` restricts it to threads with a matching row; pagination is
        identical either way.

        Args:
            page: Page number (1-indexed).
            limit: Threads per page.

        Returns:
            Paginated listing of ThreadSummary DTOs.
        """
        scope = ThreadScope.from_query()
        query = request.args.get("q", "")
        threads = Transcript.recent_threads(
            scope.channel,
            exclude_roles=self._EXCLUDE_ROLES,
            limit=limit,
            offset=(page - 1) * limit,
            query=query,
        )
        total = Transcript.count_turns(scope.channel, exclude_roles=self._EXCLUDE_ROLES, query=query)
        return ThreadSummary.listing(
            self._summaries(threads, scope), page=page, limit=limit, total=total,
        )

    def get(self, id: int | str) -> ResponseReturnValue:
        """One turn's full block — the websocket-refetch and expand-on-click
        read. One fetch fully determines a turn's render.

        Args:
            id: Turn id.

        Returns:
            The TurnBlock for this turn on the scoped channel.
        """
        scope = ThreadScope.from_query()
        block = _serializer().serialize(scope.channel, cast("int", id), scope.type)
        return TurnBlock.model_validate(block).single()

    def post(self, id: int | str, data: Request | None) -> ResponseReturnValue:
        """Send — the one chat-dispatch chokepoint. ``-1`` is the
        MessageProcessor's own unset sentinel and starts a new thread (a fresh
        turn_id is allocated synchronously); a real id replies INTO that thread
        (the id is echoed back). A supplied id naming no existing turn is
        rejected by the constructor.

        The body is multipart/form-data — ``text``, ``type``, ``thinking_level``
        and repeatable ``files`` parts — so it is read here rather than through
        a request DTO, which cannot hold many uploads under one field.

        Args:
            id: Turn id; ``-1`` starts a new thread.
            data: Unused — this endpoint declares no JSON request DTO.

        Returns:
            The turn's freshly-opened TurnExecution row.
        """
        from controllers.message_processor import MessageProcessor  # noqa: PLC0415

        scope = ThreadScope.from_form()
        attachments = self._stage_uploads(
            cast("list[object]", request.files.getlist("files")[:self._MAX_FILES]),
        )
        text = request.form.get("text", "").strip()
        if not text and not attachments:
            return Response.failure(self._MSG_REQUIRED), 422
        if not text:
            text = self._FILE_PLACEHOLDER

        # ``type`` selects the ProcessorConfig directly (user → UserConfig,
        # scheduled → ScheduledConfig on the schedule channel). Forked-ness is
        # derived internally by the MessageProcessor from the turn_id.
        payload: dict[str, object] = {
            "attachments": attachments,
            "thinking_level": request.form.get("thinking_level"),
        }
        mp = MessageProcessor.process(scope.config, text, payload, cast("int", id))
        if mp.execution is None:
            return Response.failure("Failed to open turn execution"), 500
        return TurnExecution.model_validate(mp.execution.to_dict()).single()

    def delete(self, id: int | str) -> ResponseReturnValue:
        """Interrupt the running turn for this turn_id — the stop button's call.

        Stamps the turn's open execution row CANCELLED synchronously
        (:meth:`TurnExecutionService.cancel`, the single authority for a turn's
        terminal state) and broadcasts that row on the same lifecycle websocket
        channel every other state flip uses, so the surface's ``cancelled``
        frame fires the instant this returns rather than waiting on the still
        running step loop. The loop keeps its in-flight provider call running —
        there is no mid-flight abort — but its own cancel checkpoint observes
        ``cancel_requested`` and discards the response instead of storing it;
        every row the turn already wrote stays, nothing is deleted.

        Args:
            id: Turn id — the same one the send handed back.

        Returns:
            TurnStopResult ack — cancelled=True on success, else
            reason="no_active_turn" (always 200).
        """
        from controllers.message_processor import MessageProcessor  # noqa: PLC0415

        scope = ThreadScope.from_query()
        mp = MessageProcessor(scope.config, cast("int", id))  # inert: 0 db, 0 ws at construction
        if mp.turn_execution_service.cancel() is None:
            return TurnStopResult(reason="no_active_turn").single()
        logger.info("[Threads API] cancel requested for turn %s channel=%s", id, scope.channel)
        return TurnStopResult(cancelled=True).single()

    # ── internals ─────────────────────────────────────────────────────────

    def _summaries(self, threads: list[dict[str, object]], scope: ThreadScope) -> list[ThreadSummary]:
        """Project raw ``recent_threads`` rows into feed DTOs, bulk-injecting
        each thread's one-sentence gist. Every summary is stamped with the
        scope's config type so a client refetching a thread found here carries
        the right type forward. The internal recency sort key is dropped."""
        if not threads:
            return []

        turn_ids = [cast("int", t["turn_id"]) for t in threads if t.get("turn_id") is not None]
        gists = _serializer().bulk_gists(scope.channel, turn_ids)
        return [
            ThreadSummary(
                turn_id=cast("int | None", t.get("turn_id")),
                last_activity_at=cast("str | None", t.get("last_activity_at")),
                preview=cast("str", t.get("preview") or ""),
                row_count=cast("int", t["row_count"]),
                gist=gists.get(cast("int", t["turn_id"])) if t.get("turn_id") is not None else None,
                working=bool(t.get("working", False)),
                type=scope.type,
            )
            for t in threads
        ]

    def _stage_uploads(self, files: Sequence[object]) -> list[object]:
        """Stage each uploaded chat file into tmp-storage and return the tmp
        paths. They are consumed inside
        :meth:`~controllers.message_processor.MessageProcessor._land_attachments`
        (synchronously inside ``begin``, before the ``working`` frame is
        emitted): each file is saved via
        :class:`~services.file_parser_service.FileParserService.place` into
        ``data/documents/uploads/``, the ``transcript_files`` link row is
        written, and the tmp file is removed. Then on turn zero each stored
        path is indexed and dispatched as ``vision`` (images) or ``read``
        (everything else). No file blob ever reaches the act-trail — only the
        extracted text or vision description does."""
        from services.filename_utils import safe_filename  # noqa: PLC0415
        from services.tmp_storage import new_tmp_path  # noqa: PLC0415

        paths: list[object] = []
        for f in files:
            if not f or not getattr(f, "filename", None):
                continue
            name = safe_filename(getattr(f, "filename")) or "attachment"
            tmp_path = new_tmp_path(f"{uuid.uuid4().hex[:8]}_{name}")
            getattr(f, "save")(tmp_path)
            paths.append(tmp_path)
        return paths
