"""REST endpoints for the wrappers namespace — external bearer-token management.

Wrappers are external API tokens (e.g. Anthropic, OpenAI) that Chalie uses to
act on behalf of the user. Each wrapper has a name, metadata, and a raw token
that is shown exactly once on creation (never on reads).

Routes (generated by the Endpoint base):
    POST   /api/wrappers/-1           Create a new wrapper token (create sentinel)
    GET    /api/wrappers/all          List all non-revoked wrappers (paginated)
    GET    /api/wrappers/<id>         Fetch a single wrapper by ID
    DELETE /api/wrappers/<id>         Revoke a wrapper token

Cookie-only constraint: POST is cookie-only (not bearer) to prevent
cross-origin token theft. The base class enforces this via
``cookie_only_methods``.
"""

from __future__ import annotations

from datetime import datetime
from typing import ClassVar, cast

from api.request import Request
from api.request.wrapper import WrapperCreate
from api.response.wrapper import Wrapper, WrapperCreated
from api.endpoint import Endpoint, EndpointError, NotFoundError
from flask.typing import ResponseReturnValue
from services.wrapper_auth_service import WrapperAuthService


class WrappersEndpoint(Endpoint):
    """REST endpoints for external wrapper token management.

    Wrappers are external API tokens (e.g. Anthropic, OpenAI) that Chalie uses
    to act on behalf of the user. Each wrapper has a name, metadata, and a raw
    token that is shown exactly once on creation (never on reads).

    The POST endpoint is cookie-only to prevent cross-origin token theft — the
    base class enforces this via ``cookie_only_methods``.
    """

    id_type: ClassVar[type[int] | type[str]] = str
    cookie_only_methods: ClassVar[frozenset[str]] = frozenset({"post"})
    request_dto: ClassVar[type[Request] | None] = WrapperCreate

    def slug(self) -> str:
        return "wrappers"

    def _service(self) -> WrapperAuthService:
        return WrapperAuthService()

    def post(self, id: int | str, data: Request | None) -> ResponseReturnValue:
        """Create a new wrapper token.

        Mint a new external API token and return the raw secret (shown once).
        Cookie-only to prevent cross-origin token theft.

        Args:
            id: Ignored (create route uses -1).
            data: WrapperCreate with name and metadata.

        Returns:
            WrapperCreated with the raw token.
        """
        if not self.is_create(id):
            return self.not_allowed()

        if not isinstance(data, WrapperCreate):
            raise EndpointError("Missing request body")

        raw_token, wrapper_id = self._service().create_token(
            name=data.name,
            metadata=data.metadata,
        )
        return WrapperCreated(wrapper_id=wrapper_id, token=raw_token).single(), 201

    def get_all(self, page: int = 1, limit: int = 20) -> ResponseReturnValue:
        """List all non-revoked wrappers.

        Args:
            page: Page number (1-indexed).
            limit: Items per page.

        Returns:
            Paginated list of Wrapper DTOs.
        """
        all_wrappers = self._service().list_wrappers()
        items = [
            Wrapper(
                id=cast(str, row["id"]),
                wrapper_id=cast(str, row["wrapper_id"]),
                name=cast(str, row["name"]),
                metadata=cast(dict[str, object], row["metadata"]),
                last_seen_at=cast(datetime | None, row["last_seen_at"]),
                created_at=cast(datetime, row["created_at"]),
            )
            for row in all_wrappers
        ]
        total = len(items)
        start = (page - 1) * limit
        end = start + limit
        page_items = items[start:end]
        return Wrapper.listing(page_items, page=page, limit=limit, total=total)

    def get(self, id: int | str) -> ResponseReturnValue:
        """Fetch a single wrapper by ID.

        Args:
            id: Wrapper UUID.

        Returns:
            Wrapper DTO with metadata.

        Raises:
            NotFoundError: If wrapper not found.
        """
        wrapper = self._service().get_wrapper(cast(str, id))
        if wrapper is None:
            raise NotFoundError("Wrapper not found")
        return Wrapper(
            id=cast(str, wrapper["id"]),
            wrapper_id=cast(str, wrapper["wrapper_id"]),
            name=cast(str, wrapper["name"]),
            metadata=cast(dict[str, object], wrapper["metadata"]),
            last_seen_at=cast(datetime | None, wrapper["last_seen_at"]),
            created_at=cast(datetime, wrapper["created_at"]),
        ).single()

    def delete(self, id: int | str) -> ResponseReturnValue:
        """Revoke a wrapper token.

        Args:
            id: Wrapper UUID.

        Raises:
            NotFoundError: If wrapper not found.

        Returns:
            204 No Content on success (no body).
        """
        if not self._service().revoke(cast(str, id)):
            raise NotFoundError("Wrapper not found")
        return "", 204
