"""Swagger bridge — register Pydantic DTOs into the flask-restx ``Api``.

flask-restx serves OpenAPI 2.0, whose ``$ref`` targets live under
``#/definitions/{model}``. Pydantic v2 emits JSON Schema 2020-12 with nested
models under ``$defs``; :meth:`OpenApiRegistry.register_dto` lifts those into
separately registered top-level definitions so every ``$ref`` resolves, then
registers the DTO itself under its class name.

Attach a registered model to a route with the one-liner the namespaces reuse::

    OpenApiRegistry.register_dto(api, ListItem, ListItemCreate)
    @ns.response(200, "The item", model=api.models["ListItem"])
    @ns.expect(api.models["ListItemCreate"])

:meth:`OpenApiRegistry.register_envelope` and :meth:`OpenApiRegistry.register_error_envelope` build on
the same bridge to document the response *envelope* (``{"success", "result",
...}``) that :class:`api.response.response.Response` wraps every DTO in —
the ``Endpoint``/``Action`` base contract's generated routes never emit a
bare DTO, so documenting the DTO alone would misdescribe the wire shape.

:meth:`OpenApiRegistry.register_auth_error` documents a third, deliberately different shape:
``api.auth.require_auth`` rejects an unauthenticated request with a bare
``{"error": str}`` body before dispatch ever reaches an endpoint/action, so a
401 is never wrapped in the ``{success, result, error}`` envelope every other
failure uses.
"""

from __future__ import annotations

from typing import Protocol

from pydantic import BaseModel

from .base import DTO


class _SchemaRegistrar(Protocol):
    """Structural type for the flask-restx ``Api``/``Namespace`` model-registration surface."""

    def schema_model(self, name: str, schema: dict[str, object]) -> object: ...


_ERROR_ENVELOPE_NAME = "ErrorEnvelope"
"""Model name for the uniform error envelope — one definition, shared by every namespace."""

_AUTH_ERROR_NAME = "AuthError"
"""Model name for the bare authentication-failure body — one definition,
shared by every namespace, distinct from :data:`_ERROR_ENVELOPE_NAME`."""


class OpenApiRegistry:
    """Pure-static registry for swagger/OpenAPI schema models.

    Every method is a ``@staticmethod`` — the class holds no state and is
    imported as a single namespace for all swagger-wiring calls.
    """

    @staticmethod
    def _to_swagger_schema(model_cls: type[BaseModel]) -> dict[str, object]:
        """Render a Pydantic model as an OpenAPI 2.0 schema with definition-scoped ``$ref``s."""
        return model_cls.model_json_schema(ref_template="#/definitions/{model}")

    @staticmethod
    def register_dto(api: _SchemaRegistrar, *dto_classes: type[DTO]) -> None:
        """Register each DTO and its nested models as top-level flask-restx schema models."""
        for dto_cls in dto_classes:
            schema = OpenApiRegistry._to_swagger_schema(dto_cls)
            defs = schema.pop("$defs", {})
            if isinstance(defs, dict):
                for def_name, def_schema in defs.items():
                    api.schema_model(def_name, def_schema)
            api.schema_model(dto_cls.__name__, schema)

    @staticmethod
    def _error_envelope_schema() -> dict[str, object]:
        """OpenAPI 2.0 schema for :meth:`Response.failure`'s ``{success, result, error}`` body."""
        return {
            "type": "object",
            "properties": {
                "success": {"type": "boolean", "enum": [False]},
                "result": {"type": "array", "items": {}},
                "error": {"type": "string"},
            },
            "required": ["success", "result", "error"],
        }

    @staticmethod
    def register_error_envelope(api: _SchemaRegistrar) -> str:
        """Register the uniform error envelope model (idempotent); return its name.

        Every non-2xx generated by :meth:`Endpoint._guard`/:meth:`Endpoint.not_allowed`
        shares this one shape, so it is registered once per namespace rather than
        once per DTO.
        """
        api.schema_model(_ERROR_ENVELOPE_NAME, OpenApiRegistry._error_envelope_schema())
        return _ERROR_ENVELOPE_NAME

    @staticmethod
    def _auth_error_schema() -> dict[str, object]:
        """OpenAPI 2.0 schema for ``require_auth``'s bare ``{"error": str}`` body."""
        return {
            "type": "object",
            "properties": {"error": {"type": "string"}},
            "required": ["error"],
        }

    @staticmethod
    def register_auth_error(api: _SchemaRegistrar) -> str:
        """Register the bare auth-failure model (idempotent); return its name.

        Every route's 401 shares this one shape — ``require_auth`` runs before any
        endpoint/action dispatch, so it is registered once per namespace rather
        than derived from :meth:`register_error_envelope`.
        """
        api.schema_model(_AUTH_ERROR_NAME, OpenApiRegistry._auth_error_schema())
        return _AUTH_ERROR_NAME

    @staticmethod
    def _single_envelope_schema(dto_name: str) -> dict[str, object]:
        """OpenAPI 2.0 schema for :meth:`Response.single`'s ``{success, result}`` body."""
        return {
            "type": "object",
            "properties": {
                "success": {"type": "boolean", "enum": [True]},
                "result": {"$ref": f"#/definitions/{dto_name}"},
            },
            "required": ["success", "result"],
        }

    @staticmethod
    def _listing_envelope_schema(dto_name: str) -> dict[str, object]:
        """OpenAPI 2.0 schema for :meth:`Response.listing`'s ``{success, result, pagination}`` body."""
        return {
            "type": "object",
            "properties": {
                "success": {"type": "boolean", "enum": [True]},
                "result": {
                    "type": "array",
                    "items": {"$ref": f"#/definitions/{dto_name}"},
                },
                "pagination": {
                    "type": "object",
                    "properties": {
                        "page": {"type": "integer"},
                        "limit": {"type": "integer"},
                        "total": {"type": "integer"},
                    },
                    "required": ["page", "limit", "total"],
                },
            },
            "required": ["success", "result", "pagination"],
        }

    @staticmethod
    def register_envelope(api: _SchemaRegistrar, dto_cls: type[DTO], *, listing: bool) -> str:
        """Register the envelope wrapping ``dto_cls`` at ``result``; return the model name.

        ``listing=True`` builds the paginated-collection envelope (``result`` is an
        array plus a ``pagination`` block, matching :meth:`Response.listing`);
        ``listing=False`` builds the single-resource envelope
        (:meth:`Response.single`). ``dto_cls`` must already be registered via
        :meth:`register_dto` so the inner ``$ref`` resolves.
        """
        suffix = "ListingEnvelope" if listing else "Envelope"
        name = f"{dto_cls.__name__}{suffix}"
        schema = (
            OpenApiRegistry._listing_envelope_schema(dto_cls.__name__)
            if listing
            else OpenApiRegistry._single_envelope_schema(dto_cls.__name__)
        )
        api.schema_model(name, schema)
        return name
